# Definicao completa dos Caminhos e Sequencias
# Cada Sequencia tem 9 niveis, com titulo, descricao e requisitos de progressao
# Baseado em principios de psicologia, terapia, neurociencia e filosofia

PATHS = {
    "FOOL": {
        "name": "O Louco",
        "archetype": "Filosofo / Viajante",
        "description": (
            "O Caminho do Louco e a trajetoria do pensamento nao-linear. "
            "O Louco nao teme o caos -- ele o habita. Psicologicamente, este caminho "
            "trabalha a tolerancia a incerteza, a criatividade e a capacidade de reframing. "
            "Filosoficamente, orbita o estoicismo e o zen. Nutricionalmente, foca na saude "
            "cerebral e na plasticidade neural."
        ),
        "levels": [
            {"level": 9, "title": "Estudante do Caos",
             "description": "Aprende a observar sem julgar. Pratica 7+ dias de journaling.",
             "potion": "Pocao da Clareza Mental",
             "ingredients": ["journaling", "meditacao", "sono_7h", "leitura_20min"],
             "digestion_threshold": 35.0,
             "xp_required": 100},
            {"level": 8, "title": "Caminhante das Margens",
             "description": "Aprende a habitar a ambiguidade. Desenvolve tolerancia a frustacao.",
             "potion": "Pocao da Resiliencia",
             "ingredients": ["exercicio_aerobico", "terapia_cognitiva", "jejum_intermitente", "leitura_filosofia"],
             "digestion_threshold": 45.0,
             "xp_required": 250},
            {"level": 7, "title": "Vagante da Nevoa",
             "description": "Comeca a reconhecer seus padroes automaticos.",
             "potion": "Pocao da Auto-Observacao",
             "ingredients": ["meditacao_20min", "diario_de_sombra", "banho_frio", "nutricao_anti_inflamacao"],
             "digestion_threshold": 55.0,
             "xp_required": 500},
            {"level": 6, "title": "Interprete de Sonhos",
             "description": "Integra o inconsciente. Trabalha com arquetipos junguianos.",
             "potion": "Pocao da Integracao",
             "ingredients": ["analise_de_sonhos", "criatividade_diaria", "contato_natureza", "omega3"],
             "digestion_threshold": 62.0,
             "xp_required": 900},
            {"level": 5, "title": "Contador de Historias",
             "description": "Reescreve a narrativa de si mesmo. Terapia narrativa aplicada.",
             "potion": "Pocao da Narrativa",
             "ingredients": ["escrita_criativa", "grupo_de_apoio", "psicoterapia", "cognicao_expandida"],
             "digestion_threshold": 68.0,
             "xp_required": 1500},
            {"level": 4, "title": "Arquiteto de Realidades",
             "description": "Cria contextos, nao apenas reage a eles.",
             "potion": "Pocao da Criacao",
             "ingredients": ["projeto_criativo", "mentoria", "nutricao_de_precisao", "exposicao_ao_frio"],
             "digestion_threshold": 74.0,
             "xp_required": 2500},
            {"level": 3, "title": "Portador do Enigma",
             "description": "Vive confortavelmente com perguntas sem resposta.",
             "potion": "Pocao da Paradoxo",
             "ingredients": ["contemplacao_filosofica", "servico_ao_proximo", "jejum_extended", "silencio_diario"],
             "digestion_threshold": 80.0,
             "xp_required": 4000},
            {"level": 2, "title": "Tecedor de Labirintos",
             "description": "Guia outros sem impor direcao. Lideranca silenciosa.",
             "potion": "Pocao da Presenca",
             "ingredients": ["mentoria_ativa", "pratica_contemplativa_avancada", "biohacking_avancado", "integracao_sombra"],
             "digestion_threshold": 88.0,
             "xp_required": 6500},
            {"level": 1, "title": "Guardiao da Nevoa",
             "description": "Maestria completa. Vive entre mundos, serve sem apego.",
             "potion": "Pocao da Transcendencia",
             "ingredients": ["servico_incondicional", "sabedoria_encarnada", "equilibrio_perfeito", "presenca_total"],
             "digestion_threshold": 95.0,
             "xp_required": 10000},
        ]
    },
    "OBSERVER": {
        "name": "O Observador",
        "archetype": "Psicologo / Analista",
        "description": (
            "O Caminho do Observador e a trajetoria do autoconhecimento radical. "
            "Fundamentado em psicologia clinica, neurociencia cognitiva e analise comportamental. "
            "O Observador aprende a ler padroes -- em si mesmo e nos outros -- com precisao cirurgica."
        ),
        "levels": [
            {"level": 9, "title": "Percebedor de Padroes",
             "description": "Aprende a notar sem reagir. Primeiros passos do meta-awareness.",
             "potion": "Pocao da Atencao Plena",
             "ingredients": ["meditacao_mindfulness", "diario_emocional", "sono_regular", "leitura_psicologia"],
             "digestion_threshold": 35.0,
             "xp_required": 100},
            {"level": 8, "title": "Mapeador de Emocoes",
             "description": "Desenvolve vocabulario emocional. Identifica gatilhos com precisao.",
             "potion": "Pocao da Inteligencia Emocional",
             "ingredients": ["psicoterapia", "journaling_emocional", "exercicio_regular", "reducao_acucar"],
             "digestion_threshold": 45.0,
             "xp_required": 250},
            {"level": 7, "title": "Detetive da Psique",
             "description": "Traca conexoes entre infancia, crencas e comportamentos atuais.",
             "potion": "Pocao das Raizes",
             "ingredients": ["terapia_profunda", "genograma_familiar", "nutricao_para_cerebro", "meditacao_avancada"],
             "digestion_threshold": 55.0,
             "xp_required": 500},
            {"level": 6, "title": "Arquivista do Inconsciente",
             "description": "Acessa e integra material reprimido de forma segura.",
             "potion": "Pocao da Integracao Profunda",
             "ingredients": ["trabalho_de_sombra", "terapia_somatica", "jejum_e_clareza", "escrita_automatica"],
             "digestion_threshold": 62.0,
             "xp_required": 900},
            {"level": 5, "title": "Decodificador de Linguagem",
             "description": "Le o que nao e dito. Comunicacao nao-verbal e micro-expressoes.",
             "potion": "Pocao da Escuta Profunda",
             "ingredients": ["treinamento_comunicacao", "supervisao_clinica", "omega3_dha", "pratica_de_escuta"],
             "digestion_threshold": 68.0,
             "xp_required": 1500},
            {"level": 4, "title": "Espelho Vivo",
             "description": "Reflete a verdade do outro sem distorcao propria.",
             "potion": "Pocao da Transparencia",
             "ingredients": ["supervisionamento_avancado", "terapia_pessoal_intensa", "nutricao_funcional", "silencio_contemplativo"],
             "digestion_threshold": 74.0,
             "xp_required": 2500},
            {"level": 3, "title": "Navegador da Psique",
             "description": "Transita entre estados de consciencia com fluencia.",
             "potion": "Pocao da Fluidez Mental",
             "ingredients": ["praticas_contemplativas_avancadas", "estudos_de_caso_avancados", "biohacking_cognitivo", "mentoria_clinica"],
             "digestion_threshold": 80.0,
             "xp_required": 4000},
            {"level": 2, "title": "Curador de Almas",
             "description": "Facilita transformacoes profundas em outros.",
             "potion": "Pocao da Cura Profunda",
             "ingredients": ["clinica_avancada", "pesquisa_ativa", "longevidade_e_saude", "presenca_terapeutica"],
             "digestion_threshold": 88.0,
             "xp_required": 6500},
            {"level": 1, "title": "Leitor de Almas",
             "description": "Ve alem da mascara. Compreende o ser sem julgamento.",
             "potion": "Pocao da Onisciencia Compassiva",
             "ingredients": ["sabedoria_clinica", "servico_humanitario", "equilibrio_perfeito", "presenca_plena"],
             "digestion_threshold": 95.0,
             "xp_required": 10000},
        ]
    },
    "ALCHEMIST": {
        "name": "O Alquimista",
        "archetype": "Nutricionista / Curandeiro",
        "description": (
            "O Caminho do Alquimista e a trajetoria da transmutacao corporal e quimica interna. "
            "Fundamentado em nutrição funcional, medicina integrativa e bioquimica. "
            "O Alquimista trata o corpo como laboratorio e aprende a otimizar cada sistema."
        ),
        "levels": [
            {"level": 9, "title": "Preparador de Ervas",
             "description": "Aprende os fundamentos da nutricao e do metabolismo.",
             "potion": "Pocao da Limpeza Inicial",
             "ingredients": ["hidratacao_3L", "eliminar_ultraprocessados", "sono_8h", "caminhada_diaria"],
             "digestion_threshold": 35.0,
             "xp_required": 100},
            {"level": 8, "title": "Aprendiz do Caldeiron",
             "description": "Aprende a ler o proprio corpo. Biofeedback basico.",
             "potion": "Pocao da Consciencia Corporal",
             "ingredients": ["diario_alimentar", "exercicio_resistencia", "jejum_16_8", "reducao_inflamacao"],
             "digestion_threshold": 45.0,
             "xp_required": 250},
            {"level": 7, "title": "Destilador de Essencias",
             "description": "Comeca a personalizar a nutricao para seu biotipo.",
             "potion": "Pocao da Personalizacao",
             "ingredients": ["exames_laboratoriais", "nutricao_ortomolecular", "suplementacao_inteligente", "treino_periodizado"],
             "digestion_threshold": 55.0,
             "xp_required": 500},
            {"level": 6, "title": "Manipulador de Elementos",
             "description": "Entende como emocoes afetam a bioquimica e vice-versa.",
             "potion": "Pocao da Conexao Mente-Corpo",
             "ingredients": ["psiconeuroimunologia", "adaptogenios", "jejum_extended", "crioterapia"],
             "digestion_threshold": 62.0,
             "xp_required": 900},
            {"level": 5, "title": "Mestre das Infusoes",
             "description": "Otimiza ciclos circadianos, hormônios e neurotransmissores.",
             "potion": "Pocao dos Ciclos",
             "ingredients": ["cronobiologia_aplicada", "otimizacao_hormonal", "nutricao_de_precisao", "exposicao_ao_sol"],
             "digestion_threshold": 68.0,
             "xp_required": 1500},
            {"level": 4, "title": "Criador de Elixires",
             "description": "Cria protocolos personalizados de alta performance.",
             "potion": "Pocao da Alta Performance",
             "ingredients": ["biohacking_avancado", "jejum_prolongado", "otimizacao_cognitiva", "recuperacao_ativa"],
             "digestion_threshold": 74.0,
             "xp_required": 2500},
            {"level": 3, "title": "Arquiteto Molecular",
             "description": "Entende e modula a propria epigenetica.",
             "potion": "Pocao da Expressao Genica",
             "ingredients": ["epigenetica_aplicada", "longevidade_avancada", "praticas_contemplativas", "nutricao_terapeutica"],
             "digestion_threshold": 80.0,
             "xp_required": 4000},
            {"level": 2, "title": "Transmutador de Vidas",
             "description": "Ajuda outros a transformarem sua biologia e comportamento.",
             "potion": "Pocao da Transmutacao Coletiva",
             "ingredients": ["clinica_nutricional", "pesquisa_funcional", "mentoria_de_saude", "integracao_total"],
             "digestion_threshold": 88.0,
             "xp_required": 6500},
            {"level": 1, "title": "Transmutador",
             "description": "Maestria completa sobre a quimica da vida.",
             "potion": "Pocao da Imortalidade Relativa",
             "ingredients": ["sabedoria_funcional", "impacto_coletivo", "equilibrio_bioquimico", "longevidade_maxima"],
             "digestion_threshold": 95.0,
             "xp_required": 10000},
        ]
    },
    "GUARDIAN": {
        "name": "O Guardiao",
        "archetype": "Terapeuta / Protetor",
        "description": (
            "O Caminho do Guardiao e a trajetoria da cura e da protecao. "
            "Fundamentado em terapia humanista, psiquiatria integrativa e neuropsicologia. "
            "O Guardiao aprende primeiro a se curar -- e entao a criar espacos seguros para outros."
        ),
        "levels": [
            {"level": 9, "title": "Sentinela do Limiar",
             "description": "Aprende a reconhecer seus proprios traumas e mecanismos de defesa.",
             "potion": "Pocao da Auto-Compaixao",
             "ingredients": ["psicoterapia_semanal", "praticas_de_auto-cuidado", "sono_regular", "leitura_terapeutica"],
             "digestion_threshold": 35.0,
             "xp_required": 100},
            {"level": 8, "title": "Portador do Escudo",
             "description": "Aprende a estabelecer limites saudaveis sem culpa.",
             "potion": "Pocao dos Limites",
             "ingredients": ["trabalho_de_limites", "terapia_cognitivo_comportamental", "exercicio_e_saude", "comunidade_de_apoio"],
             "digestion_threshold": 45.0,
             "xp_required": 250},
            {"level": 7, "title": "Guardador de Almas",
             "description": "Desenvolve presenca terapeutica. Aprende a conter sem absorver.",
             "potion": "Pocao da Presenca Terapeutica",
             "ingredients": ["supervisao_clinica", "pratica_contemplativa", "nutricao_para_sistema_nervoso", "terapia_somatica"],
             "digestion_threshold": 55.0,
             "xp_required": 500},
            {"level": 6, "title": "Curador de Feridas",
             "description": "Trabalha com trauma de forma segura e estruturada.",
             "potion": "Pocao do Trauma",
             "ingredients": ["formacao_em_trauma", "EMDR_ou_equivalente", "regulacao_do_sistema_nervoso", "integracao_psicossomatica"],
             "digestion_threshold": 62.0,
             "xp_required": 900},
            {"level": 5, "title": "Arquiteto de Vinculos",
             "description": "Entende e modifica padroes de apego.",
             "potion": "Pocao do Apego Seguro",
             "ingredients": ["teoria_do_apego_aplicada", "terapia_de_casais_ou_familia", "omega3_e_cerebro", "pratica_relacional"],
             "digestion_threshold": 68.0,
             "xp_required": 1500},
            {"level": 4, "title": "Guardiao do Fogo",
             "description": "Sustenta crises sem perder o centro.",
             "potion": "Pocao da Equanimidade",
             "ingredients": ["treinamento_em_crise", "regulacao_autonoma_avancada", "nutricao_anti_stress", "pratica_diaria_profunda"],
             "digestion_threshold": 74.0,
             "xp_required": 2500},
            {"level": 3, "title": "Portador da Luz",
             "description": "Transforma ambientes pelo exemplo e pela presenca.",
             "potion": "Pocao da Irradiacao",
             "ingredients": ["lideranca_terapeutica", "pesquisa_clinica", "longevidade_integrada", "servico_ativo"],
             "digestion_threshold": 80.0,
             "xp_required": 4000},
            {"level": 2, "title": "Forjador de Santuarios",
             "description": "Cria espacos de cura duradouros e comunidades saudaveis.",
             "potion": "Pocao do Santuario",
             "ingredients": ["construcao_de_comunidade", "supervisao_de_terapeutas", "saude_sistemica", "presenca_profunda"],
             "digestion_threshold": 88.0,
             "xp_required": 6500},
            {"level": 1, "title": "Paladino da Psique",
             "description": "Maestria completa. Protege e cura sem se perder.",
             "potion": "Pocao da Totalidade",
             "ingredients": ["sabedoria_clinica", "impacto_geracional", "saude_perfeita", "amor_incondicional"],
             "digestion_threshold": 95.0,
             "xp_required": 10000},
        ]
    },
    "ARCHITECT": {
        "name": "O Arquiteto",
        "archetype": "Estrategista / Construtor",
        "description": (
            "O Caminho do Arquiteto e a trajetoria do design de sistemas e da execucao precisa. "
            "Fundamentado em psicologia cognitiva, filosofia pragmatica e neurociencia da tomada de decisao. "
            "O Arquiteto aprende a construir estruturas -- internas e externas -- que funcionam sob pressao."
        ),
        "levels": [
            {"level": 9, "title": "Tracador de Planos",
             "description": "Aprende a criar sistemas de habitos e rotinas sustentaveis.",
             "potion": "Pocao da Disciplina",
             "ingredients": ["rotina_matinal", "planejamento_semanal", "sono_otimizado", "exercicio_consistente"],
             "digestion_threshold": 35.0,
             "xp_required": 100},
            {"level": 8, "title": "Construtor de Fundacoes",
             "description": "Identifica e elimina friccoes que sabotam o progresso.",
             "potion": "Pocao da Clareza Sistemica",
             "ingredients": ["audit_de_tempo", "eliminacao_de_distracao", "nutricao_para_foco", "deep_work_diario"],
             "digestion_threshold": 45.0,
             "xp_required": 250},
            {"level": 7, "title": "Engenheiro do Comportamento",
             "description": "Design de ambientes que facilitam comportamentos desejados.",
             "potion": "Pocao do Ambiente",
             "ingredients": ["design_de_ambiente", "psicologia_comportamental", "otimizacao_cognitiva", "recuperacao_ativa"],
             "digestion_threshold": 55.0,
             "xp_required": 500},
            {"level": 6, "title": "Estrategista da Psique",
             "description": "Usa principios psicologicos para superar resistencias internas.",
             "potion": "Pocao da Execucao",
             "ingredients": ["psicologia_da_motivacao", "terapia_de_aceitacao", "biohacking_cognitivo", "tomada_de_decisao"],
             "digestion_threshold": 62.0,
             "xp_required": 900},
            {"level": 5, "title": "Arquiteto de Sistemas",
             "description": "Cria processos que produzem resultados independentes de motivacao.",
             "potion": "Pocao dos Sistemas",
             "ingredients": ["second_brain", "automacao_de_habitos", "nutricao_de_alta_performance", "recuperacao_sistemica"],
             "digestion_threshold": 68.0,
             "xp_required": 1500},
            {"level": 4, "title": "Constructor de Legados",
             "description": "Projeta o futuro a 10-20 anos e trabalha de tras para frente.",
             "potion": "Pocao da Visao",
             "ingredients": ["planejamento_de_legado", "mentoria_de_outros", "saude_de_longo_prazo", "clareza_de_valores"],
             "digestion_threshold": 74.0,
             "xp_required": 2500},
            {"level": 3, "title": "Forjador de Realidades",
             "description": "Manifesta intencoes em estruturas concretas.",
             "potion": "Pocao da Manifestacao",
             "ingredients": ["execucao_de_alto_nivel", "lideranca_sistemica", "longevidade_avancada", "filosofia_pratica"],
             "digestion_threshold": 80.0,
             "xp_required": 4000},
            {"level": 2, "title": "Arquiteto de Civilizacoes",
             "description": "Cria sistemas que funcionam sem sua presenca constante.",
             "potion": "Pocao da Autonomia",
             "ingredients": ["construcao_de_organizacoes", "multiplicacao_de_impacto", "saude_sistemica", "sabedoria_pratica"],
             "digestion_threshold": 88.0,
             "xp_required": 6500},
            {"level": 1, "title": "Deus dos Sistemas",
             "description": "Maestria completa. Os sistemas continuam apos o criador.",
             "potion": "Pocao da Imortalidade Sistemica",
             "ingredients": ["legado_concreto", "impacto_civilizacional", "saude_perfeita", "sabedoria_encarnada"],
             "digestion_threshold": 95.0,
             "xp_required": 10000},
        ]
    }
}

def get_sequence_for_beyonder(path: str, level: int) -> dict:
    path_data = PATHS.get(path)
    if not path_data:
        return {}
    for seq in path_data["levels"]:
        if seq["level"] == level:
            return seq
    return {}

def get_next_level_requirements(path: str, current_level: int) -> dict:
    if current_level <= 1:
        return {"message": "Voce atingiu a maestria completa."}
    return get_sequence_for_beyonder(path, current_level - 1)
